language: java
sudo: false # faster builds
before_install:
- chmod +x mvnw
script:
# - "./mvnw clean install -B"
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
addons:
sonarcloud:
  organization: employee1
  token:
    secure: 3a31bf3cfad523d027590a33caed5c767453ea2d
